config/routes.rb
HomeManagement::Application.routes.draw do
devise_for :users,  :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :details do
    collection do
      get :ankit_shubham
    end
  end
  
  resources :home

  root :to => "home#index"

end

app/models/Detail.rb
class Detail < ActiveRecord::Base
  belongs_to :group
end

app/models/Group.rb
class Group < ActiveRecord::Base
  has_many :details
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.xml
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @details }
    end
  end

  def ankit_shubham
    @details = Detail.all
    @group_name= Group.find_by_name('ankit-shubham')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @details }
    end

  end
  # GET /details/1
  # GET /details/1.xml
  def show
    @detail = Detail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @detail }
    end
  end

  # GET /details/new
  # GET /details/new.xml
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = detail.find(params[:id])
  end

  # POST /details
  # POST /details.xml
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to(@detail, :notice => 'Detail was successfully created.') }
        format.xml  { render :xml => @detail, :status => :created, :location => @detail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.xml
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to(@detail, :notice => 'Detail was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.xml
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to(ankit_shubham_details_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  # GET /members
  # GET /members.xml
  def index
    @name = current_user.email.split('@').first
      end

  # GET /members/1
  # GET /members/1.xml
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :cols =>60, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/ankit_shubham.html.erb
<table style =" width: 700px;">
  <tr>
    <td>
      <%  unless @group_name.blank? %>
      <h1><%=@group_name.name%></h1>
      <%end%>
    </td>
    <td>
      <%= link_to 'New detail', new_detail_path %>
    </td>
  </tr>
</table>

<br/>
<table>
  <tr>

    <th>Description</th>

  </tr>

  <% @details.each do |detail| %>
    <tr>
      <td><%= link_to detail.description , detail %></td>
    </tr>
  <% end %>
</table>

app/views/details/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/details/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Amount</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.name %></td>
    <td><%= detail.date.to_date %></td>
    <td><%= detail.amount %></td>
    <td><%= detail.description %></td>
    <td><%= link_to 'Show', detail %></td>
    <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
    <td><%= link_to 'Destroy', detail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>
<br/>
<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @detail.name %>
</p>

<p>
  <b>Date:</b>
  <%= @detail.date %>
</p>

<p>
  <b>Amount:</b>
  <%= @detail.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @detail.description %>
</p>

<td><%= link_to 'Edit', edit_detail_path(@detail) %></td>
<td><%= link_to 'Destroy', @detail, :confirm => 'Are you sure?', :method => :delete %></td>
<%= link_to 'Back', details_path %>

app/views/home/index.html.erb
<h2>Welcome, <%= @name  %></h2>
<div class="articles">
Click on the required tab to enter your details!!
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stop-Kharcha</title>
    <%= stylesheet_link_tag 'style','jquery-ui' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "jquery.min", "jquery-ui.min" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml"/>
    <head>
      <title>1302 JKM</title>
      <meta http-equiv="Content-Language" content="English" />
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    </head>


    <div id="wrap">

      <div id="top"> </div>

      <div id="header">
        <h1><a href="#">STOP-KHARCHA</a></h1>
        <br/>
        <h2>Initiative to manage hamara kharcha.</h2>
      </div>

      <div id="menu">
        <% if user_signed_in? -%>
          <ul>
            <li><%= link_to 'Home' ,home_index_path %></li>
            <li><%= link_to 'Ankit-Shubham' ,ankit_shubham_details_path %></li>
            <li><%= link_to 'Nikhil-Shubham' ,ankit_shubham_details_path %></li>
          </ul>

          <%= current_user.email %> |
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>

        <%end%>
      </div>


      <div id="content">
        <div class="left">
          <div class="articles">

            <%= yield %>
          </div>
        </div>

        <div class="right">


          <% if user_signed_in? -%>
          <h2>Archives</h2>

            <ul>
              <li><a href="#">January 2011</a></li>
              <li><a href="#">February 2011</a></li>
              <li><a href="#">March 2011</a></li>
              <li><a href="#">April 2011</a></li>
              <li><a href="#">May 2011</a></li>
              <li><a href="#">June 2011</a></li>
              <li><a href="#">July 2011</a></li>
              <li><a href="#">August 2011</a></li>
              <li><a href="#">September 2011</a></li>
              <li><a href="#">October 2011</a></li>
              <li><a href="#">November 2011</a></li>
              <li><a href="#">December 2011</a></li>
            </ul>
          <%end%>
        </div>

        <div style="clear: both;"> </div>
      </div>

      <div id="bottom"> </div>
      <div id="footer">
        <a href="javascript(void);">Website Designed</a> by <a href="http://ankitinstinct.blogspot.com/" target="_blank">Ankit Gupta</a>
      </div>
    </div>


  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>